name: currency
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter_offline: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Menambahkan asset
  assets:
    - assets/fonts/Roboto-Regular.ttf

  # Menambahkan font
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
